import os
from dotenv import load_dotenv

assert load_dotenv(".env")


MYSQL_DATABASE = os.environ["MYSQL_DATABASE"]
assert MYSQL_DATABASE

MYSQL_USER = os.environ["MYSQL_USER"]
assert MYSQL_USER

MYSQL_PASSWORD = os.environ["MYSQL_PASSWORD"]
assert MYSQL_PASSWORD

MYSQL_HOST = os.environ["MYSQL_HOST"]
assert MYSQL_HOST

MYSQL_PORT = os.environ["MYSQL_PORT"]
assert MYSQL_PORT

AOI_OPERATOR_INITIAL_PASSWORD = os.environ["AOI_OPERATOR_INITIAL_PASSWORD"]
assert AOI_OPERATOR_INITIAL_PASSWORD

AOI_ADMINISTRATOR_INITIAL_PASSWORD = os.environ["AOI_ADMINISTRATOR_INITIAL_PASSWORD"]
assert AOI_ADMINISTRATOR_INITIAL_PASSWORD

STORAGE_SECRET = os.environ["STORAGE_SECRET"]
assert STORAGE_SECRET and len(STORAGE_SECRET) > 10

MINIO_ROOT_USER = os.environ["MINIO_ROOT_USER"]
assert MINIO_ROOT_USER

MINIO_ROOT_PASSWORD = os.environ["MINIO_ROOT_PASSWORD"]
assert MINIO_ROOT_PASSWORD

MINIO_HOST = os.environ["MINIO_HOST"]
assert MINIO_HOST

MINIO_PORT = os.environ["MINIO_PORT"]
assert MINIO_PORT

