# Moderator node inspection trigger interface (Frontend-Driven Architecture)

# Request (O que o Frontend envia para o ROS2)
int64 inspection_profile_id
sensor_msgs/Image test_image

---
# Response (O que o ROS2 devolve para o Frontend)
bool overall_passed

sensor_msgs/Image image
open_aoi_interfaces/InspectionLog[] inspection_log_list
open_aoi_interfaces/InspectionTarget[] inspection_target_list

string error
string error_description